services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - repository:/repo
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&:
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASSWORD=changeme
      - MEDIA_ROOT=/repo/files
      - SECRET_KEY=!crCG/e:iwYA{b5_8TaVT4y*d0%_uLn9tqv&X9LqYCt:;mWf,55666_@FC1Z
      - EMAIL_HOST=mail.lava.mx
      - EMAIL_PORT=587
      - EMAIL_USE_TLS=True
      - EMAIL_HOST_USER=noresponder@sisoftware.mx
      - EMAIL_HOST_PASSWORD=Ta1ute8ozjgA@zH
    depends_on:
      - db
    restart: always
  db:
    image: postgres:13-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
    restart: always
volumes:
  db-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${VOLUME_PATH}/db
  repository:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${VOLUME_PATH}/files