# Generated by Django 3.2.25 on 2024-04-12 17:00

from django.db import migrations

from django.contrib.auth.management import create_permissions
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType

from django.contrib.auth import get_user_model
from django.contrib.auth.models import Permission
from permission.views import PermissionQuerySet
from core import models

def force_create_permissions(apps, schema_editor):
    """creates permissions without waiting for post_migrate signal
    """
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, apps=apps, verbosity=0)
        app_config.models_module = None

def default_admin(apps, schema_editor):

    ## Create default group
    group, created = models.CustomGroup.objects.get_or_create(name='SuperAdmin')
    perms = PermissionQuerySet().business_domain().all()
    group.permissions.set(perms)

    ## Create default admin user
    data = {
        'name': 'Default user',
        'email': 'default@shp.com',
        'password': 'Password0.',
    }

    user = get_user_model().objects.create_user(**data)
    group.user_set.add(user)

    data = {
        'user': user,
        'job_position': 'Super Admin'
    }

    models.Profile.objects.create(**data)

def default_evidence_groups(apps, schema_editor):
    m1 = models.EvidenceGroup(name="Auditoría interna", alias="internal", description="Auditoría interna")
    m2 = models.EvidenceGroup(name="Documentos confidenciales", alias="confidencial", description="Documentos confidenciales")
    m3 = models.EvidenceGroup(name="Entregables de terceros", alias="third-party", description="Entregables de terceros")
    ms = [m1, m2, m3]
    for x in ms:
        x.save()

def default_evidence_stage(apps, schema_editor):
    m1 = models.EvidenceStage(name="Pendiente", position=10, description="Pendiente")
    m2 = models.EvidenceStage(name="En proceso", position=20, description="En proceso")
    m3 = models.EvidenceStage(name="Authorizaciones", position=30, description="Esperando authorizaciones")
    m3 = models.EvidenceStage(name="Terminado", position=40, description="Terminado")
    m3 = models.EvidenceStage(name="Archivado", position=50, description="Archivado")
    ms = [m1, m2, m3]
    for x in ms:
        x.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(force_create_permissions, migrations.RunPython.noop),
        migrations.RunPython(default_admin),
        migrations.RunPython(default_evidence_groups),
        migrations.RunPython(default_evidence_stage),
    ]
