# Generated by Django 3.2.23 on 2024-01-21 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20240121_2136'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='evidencetypecustomfield',
            unique_together={('evidence_type', 'custom_field')},
        ),
    ]
