# Generated by Django 3.2.25 on 2024-04-15 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20240412_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceQualityControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PEN', 'Pending'), ('COM', 'Completed')], default='PEN', max_length=3)),
                ('comments', models.CharField(max_length=512)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.evidence')),
                ('quality_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.qualitycontrol')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
