# Generated by Django 3.2.23 on 2024-01-17 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customgroup_department_dpe_entity_evidencegroup_evidencestage_evidencestatus_evidencetype_institutio'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencetype',
            name='attachment_required',
            field=models.BooleanField(default=True),
        ),
    ]
