# Generated by Django 3.2.23 on 2024-01-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_evidencetypecustomfield_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='catalog',
            field=models.TextField(blank=True, null=True),
        ),
    ]
