# Generated by Django 3.2.25 on 2024-04-17 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_evidencequalitycontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencequalitycontrol',
            name='resolution',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
