# Generated by Django 3.2.23 on 2024-01-28 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_description_evidencefinding_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidenceauth',
            name='status',
            field=models.CharField(choices=[('PEN', 'Pending'), ('COM', 'Completed')], default='PEN', max_length=3),
        ),
        migrations.AlterField(
            model_name='evidencesignature',
            name='status',
            field=models.CharField(choices=[('PEN', 'Pending'), ('COM', 'Completed')], default='PEN', max_length=3),
        ),
    ]
