# Generated by Django 3.2.25 on 2024-05-02 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20240424_0353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evidence',
            options={'permissions': [('work_evidence', 'Daily work for non manager users'), ('manage_evidence', 'Daily work for manager users'), ('generate_evidence_reports', 'Generate evidence reports')]},
        ),
        migrations.CreateModel(
            name='ResetPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=512)),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
