# Generated by Django 3.2.23 on 2024-01-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20240120_1435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customfield',
            options={'verbose_name': 'Custom field', 'verbose_name_plural': 'Custom field'},
        ),
        migrations.AddField(
            model_name='customfield',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
