# Generated by Django 3.2.25 on 2024-05-13 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20240501_2249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'permissions': [('import_department', 'Import departments')], 'verbose_name': 'SHP Department', 'verbose_name_plural': 'SHP Departments'},
        ),
        migrations.AlterModelOptions(
            name='dpe',
            options={'permissions': [('import_dpe', 'Import Dpes')], 'verbose_name': 'Decentralized public entity', 'verbose_name_plural': 'Decentralized public entities'},
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'permissions': [('import_entity', 'Import Entities')], 'verbose_name': 'Entity', 'verbose_name_plural': 'Entities'},
        ),
        migrations.AlterModelOptions(
            name='municipality',
            options={'permissions': [('import_municipality', 'Import Municipalities')], 'verbose_name': 'Municipality', 'verbose_name_plural': 'Municipalities'},
        ),
        migrations.AlterModelOptions(
            name='sianuser',
            options={'permissions': [('import_sianuser', 'Import SIAN')], 'verbose_name': 'SIAN user', 'verbose_name_plural': 'SIAN users'},
        ),
        migrations.AlterModelOptions(
            name='sifuser',
            options={'permissions': [('import_sifuser', 'Import SIIF')], 'verbose_name': 'SIF user', 'verbose_name_plural': 'SIF users'},
        ),
        migrations.AlterModelOptions(
            name='stateorg',
            options={'permissions': [('import_stateorg', 'Import State Orgs')], 'verbose_name': 'State Organization', 'verbose_name_plural': 'State organizations'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'permissions': [('import_supplier', 'Import Suppliers')], 'verbose_name': 'Supplier'},
        ),
    ]
