# Generated by Django 3.2.23 on 2024-01-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customfield_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencetype',
            name='auth_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evidencetype',
            name='signature_required',
            field=models.BooleanField(default=False),
        ),
    ]
