# Generated by Django 3.2.25 on 2024-05-23 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20240512_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary', models.TextField()),
                ('secondary', models.TextField()),
                ('terciary', models.TextField()),
                ('quaternary', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
