# Generated by Django 3.2.23 on 2024-01-06 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_municipality'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
