# Generated by Django 3.2.23 on 2024-01-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20240126_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencetypecustomfield',
            name='group',
            field=models.CharField(default='General', max_length=64),
        ),
    ]
