# Generated by Django 3.2.23 on 2024-01-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_municipality_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name': 'Institution',
            },
        ),
        migrations.AlterModelOptions(
            name='municipality',
            options={'verbose_name': 'Municipality', 'verbose_name_plural': 'Municipalities'},
        ),
    ]
