# Generated by Django 3.2.23 on 2024-01-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20240107_0544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dpe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name': 'Decentralized public entity',
                'verbose_name_plural': 'Decentralized public entities',
            },
        ),
    ]
