# Generated by Django 3.2.23 on 2024-03-20 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20240320_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.evidence'),
        ),
    ]
