# Generated by Django 3.2.23 on 2024-01-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_dpe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('tax_id', models.CharField(max_length=13, unique=True)),
                ('tax_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Supplier',
            },
        ),
    ]
