# Generated by Django 3.2.25 on 2024-03-27 12:46

from django.db import migrations

from django.contrib.auth.management import create_permissions
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType

from django.contrib.auth import get_user_model
from django.contrib.auth.models import Permission
from permission.views import PermissionQuerySet
from core import models

def force_create_permissions(apps, schema_editor):
    """creates permissions without waiting for post_migrate signal
    """
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, apps=apps, verbosity=0)
        app_config.models_module = None

def default_admin(apps, schema_editor):

    ## Create default group
    group, created = models.CustomGroup.objects.get_or_create(name='SuperAdmin')
    perms = PermissionQuerySet().business_domain().all()
    group.permissions.set(perms)

    ## Create default admin user
    data = {
        'name': 'Default user',
        'email': 'default@shp.com',
        'password': 'Password0.',
    }

    user = get_user_model().objects.create_user(**data)
    group.user_set.add(user)

    data = {
        'user': user,
        'job_position': 'Super Admin'
    }

    models.Profile.objects.create(**data)

# def default_permissions(apps, schema_editor):
#     group = models.CustomGroup.objects.get(name='SuperAdmin')
#     perms = PermissionQuerySet().business_domain().all()
#     group.permissions.set(perms)
#     pass

class Migration(migrations.Migration):    
    dependencies = [
        ('core', '0009_evidence_parent'),
    ]

    operations = [
        migrations.RunPython(force_create_permissions, migrations.RunPython.noop),
        migrations.RunPython(default_admin),
        # migrations.RunPython(default_permissions),
    ]
