# Generated by Django 3.2.25 on 2024-03-27 13:25

import core.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20240327_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='uploads/'), upload_to=core.models.get_upload_path),
        ),
    ]
