# Generated by Django 3.2.25 on 2024-04-03 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_evidencecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualitycontrol',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='qualitycontrol',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='EvidenceTypeQualityControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quality_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.qualitycontrol')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.evidencetype')),
            ],
            options={
                'unique_together': {('type', 'quality_control')},
            },
        ),
        migrations.RemoveField(
            model_name='qualitycontrol',
            name='type',
        ),
        migrations.AddField(
            model_name='evidencetype',
            name='quality_controls',
            field=models.ManyToManyField(through='core.EvidenceTypeQualityControl', to='core.QualityControl'),
        ),
    ]
