# Generated by Django 3.2.25 on 2024-04-03 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20240403_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencefinding',
            name='qc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.evidencetypequalitycontrol'),
        ),
    ]
