# Generated by Django 3.2.23 on 2024-01-12 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_sianuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('position', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Evidence stage',
                'verbose_name_plural': 'Evidence stages',
            },
        ),
        migrations.CreateModel(
            name='EvidenceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('alias', models.SlugField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Evidence type',
                'verbose_name_plural': 'Evidence types',
            },
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EvidenceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('position', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.TextField()),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.evidencestage')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.evidencetype')),
            ],
            options={
                'verbose_name': 'Evidence satatus',
                'verbose_name_plural': 'Evidence satatuses',
            },
        ),
    ]
